// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book_service.proto

package book_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookId struct {
	BookId               string   `protobuf:"bytes,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookId) Reset()         { *m = BookId{} }
func (m *BookId) String() string { return proto.CompactTextString(m) }
func (*BookId) ProtoMessage()    {}
func (*BookId) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e7ae879762c70a, []int{0}
}

func (m *BookId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookId.Unmarshal(m, b)
}
func (m *BookId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookId.Marshal(b, m, deterministic)
}
func (m *BookId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookId.Merge(m, src)
}
func (m *BookId) XXX_Size() int {
	return xxx_messageInfo_BookId.Size(m)
}
func (m *BookId) XXX_DiscardUnknown() {
	xxx_messageInfo_BookId.DiscardUnknown(m)
}

var xxx_messageInfo_BookId proto.InternalMessageInfo

func (m *BookId) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Author               string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e7ae879762c70a, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Book) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type NewBook struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBook) Reset()         { *m = NewBook{} }
func (m *NewBook) String() string { return proto.CompactTextString(m) }
func (*NewBook) ProtoMessage()    {}
func (*NewBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e7ae879762c70a, []int{2}
}

func (m *NewBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBook.Unmarshal(m, b)
}
func (m *NewBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBook.Marshal(b, m, deterministic)
}
func (m *NewBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBook.Merge(m, src)
}
func (m *NewBook) XXX_Size() int {
	return xxx_messageInfo_NewBook.Size(m)
}
func (m *NewBook) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBook.DiscardUnknown(m)
}

var xxx_messageInfo_NewBook proto.InternalMessageInfo

func (m *NewBook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewBook) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type Books struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Books) Reset()         { *m = Books{} }
func (m *Books) String() string { return proto.CompactTextString(m) }
func (*Books) ProtoMessage()    {}
func (*Books) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e7ae879762c70a, []int{3}
}

func (m *Books) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Books.Unmarshal(m, b)
}
func (m *Books) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Books.Marshal(b, m, deterministic)
}
func (m *Books) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Books.Merge(m, src)
}
func (m *Books) XXX_Size() int {
	return xxx_messageInfo_Books.Size(m)
}
func (m *Books) XXX_DiscardUnknown() {
	xxx_messageInfo_Books.DiscardUnknown(m)
}

var xxx_messageInfo_Books proto.InternalMessageInfo

func (m *Books) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *Books) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Req struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Asc                  bool     `protobuf:"varint,5,opt,name=asc,proto3" json:"asc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e7ae879762c70a, []int{4}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Req) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Req) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *Req) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Req) GetAsc() bool {
	if m != nil {
		return m.Asc
	}
	return false
}

func init() {
	proto.RegisterType((*BookId)(nil), "book_service.BookId")
	proto.RegisterType((*Book)(nil), "book_service.Book")
	proto.RegisterType((*NewBook)(nil), "book_service.NewBook")
	proto.RegisterType((*Books)(nil), "book_service.Books")
	proto.RegisterType((*Req)(nil), "book_service.Req")
}

func init() {
	proto.RegisterFile("book_service.proto", fileDescriptor_88e7ae879762c70a)
}

var fileDescriptor_88e7ae879762c70a = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0xa5, 0x5f, 0xf0, 0xb8, 0x7d, 0x79, 0x79, 0x8e, 0xa0, 0x0d, 0xab, 0xa6, 0x0b, 0xc3, 0x0a,
	0x13, 0x8c, 0x5f, 0x4b, 0xd0, 0x84, 0xb0, 0x71, 0x31, 0xc6, 0x8d, 0x1b, 0x53, 0xda, 0x8b, 0x4c,
	0xa8, 0x4c, 0x99, 0x19, 0x74, 0xe3, 0x2f, 0xf2, 0x57, 0x9a, 0x99, 0x29, 0x06, 0x02, 0x2c, 0xdc,
	0xdd, 0x73, 0xee, 0x3d, 0xbd, 0xe7, 0x9e, 0x0e, 0x90, 0x09, 0xe7, 0xf3, 0x17, 0x89, 0xe2, 0x9d,
	0x65, 0xd8, 0x2b, 0x05, 0x57, 0x9c, 0xfc, 0xdd, 0xe4, 0x92, 0x18, 0xea, 0x43, 0xce, 0xe7, 0xe3,
	0x9c, 0x9c, 0xac, 0xab, 0xc8, 0x89, 0x9d, 0x6e, 0x93, 0x56, 0x28, 0xf9, 0x04, 0x5f, 0x57, 0xe4,
	0x1f, 0xb8, 0x6c, 0xdd, 0x73, 0x59, 0x4e, 0x5a, 0x10, 0x28, 0xa6, 0x0a, 0x8c, 0x5c, 0x43, 0x59,
	0x40, 0x62, 0x08, 0x73, 0x94, 0x99, 0x60, 0xa5, 0x62, 0x7c, 0x11, 0x79, 0xa6, 0xb7, 0x49, 0x69,
	0x5d, 0x29, 0x58, 0x86, 0x91, 0x1f, 0x3b, 0xdd, 0x80, 0x5a, 0xa0, 0xb7, 0xa7, 0x2b, 0x35, 0xe3,
	0x22, 0x0a, 0xec, 0x76, 0x8b, 0x92, 0x01, 0x34, 0x1e, 0xf0, 0x63, 0xaf, 0x81, 0x33, 0xf0, 0xf5,
	0x29, 0x66, 0x7f, 0xd8, 0x27, 0xbd, 0xad, 0x5b, 0xb5, 0x82, 0x9a, 0x7e, 0x32, 0x82, 0x40, 0x23,
	0x49, 0xba, 0x10, 0x68, 0x42, 0x46, 0x4e, 0xec, 0x1d, 0x50, 0xd8, 0x01, 0xed, 0x31, 0xe3, 0xab,
	0x85, 0x32, 0xdf, 0x0e, 0xa8, 0x05, 0xc9, 0x12, 0x3c, 0x8a, 0x4b, 0x6d, 0x95, 0x4f, 0xa7, 0x12,
	0x95, 0xf1, 0x12, 0xd0, 0x0a, 0x69, 0x51, 0xc1, 0xde, 0xd8, 0x8f, 0xc8, 0x00, 0x3d, 0x2d, 0x31,
	0x15, 0xd9, 0xac, 0xca, 0xa2, 0x42, 0x84, 0x80, 0x2f, 0xb9, 0x50, 0x26, 0x85, 0x26, 0x35, 0x35,
	0xf9, 0x0f, 0x5e, 0x2a, 0x33, 0x93, 0xc0, 0x1f, 0xaa, 0xcb, 0xfe, 0x97, 0x0b, 0xa1, 0x36, 0xf6,
	0x68, 0x4d, 0x92, 0x2b, 0x80, 0x3b, 0x81, 0xa9, 0x42, 0x93, 0xc8, 0x9e, 0x0b, 0x3a, 0x7b, 0xb8,
	0xa4, 0x46, 0x2e, 0xa1, 0x31, 0x42, 0x65, 0x44, 0xad, 0xdd, 0x81, 0x71, 0x7e, 0x40, 0x76, 0x0d,
	0xe1, 0x08, 0xd5, 0xa0, 0x28, 0x6c, 0x80, 0x47, 0xdb, 0x43, 0x14, 0x97, 0x9d, 0xe3, 0x5d, 0x9d,
	0x4c, 0x6a, 0xe4, 0x16, 0xe0, 0xa9, 0xcc, 0xd7, 0x3e, 0xdb, 0xdb, 0x43, 0xd5, 0x0f, 0x3d, 0xb0,
	0xf3, 0x06, 0xe0, 0x1e, 0x0b, 0xac, 0xa4, 0xbf, 0x70, 0x3b, 0x3c, 0x7d, 0x6e, 0xbf, 0xe2, 0xc2,
	0xbc, 0xf2, 0xf3, 0xcd, 0xfe, 0xa4, 0x6e, 0xb8, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0x8e, 0x4f, 0x97, 0x0f, 0x03, 0x00, 0x00,
}
