// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_service.proto

package order_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               string   `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity             string   `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Total                string   `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Order) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type NewOrder struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrder) Reset()         { *m = NewOrder{} }
func (m *NewOrder) String() string { return proto.CompactTextString(m) }
func (*NewOrder) ProtoMessage()    {}
func (*NewOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{1}
}

func (m *NewOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrder.Unmarshal(m, b)
}
func (m *NewOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrder.Marshal(b, m, deterministic)
}
func (m *NewOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrder.Merge(m, src)
}
func (m *NewOrder) XXX_Size() int {
	return xxx_messageInfo_NewOrder.Size(m)
}
func (m *NewOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrder.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrder proto.InternalMessageInfo

func (m *NewOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewOrder) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderId struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderId) Reset()         { *m = OrderId{} }
func (m *OrderId) String() string { return proto.CompactTextString(m) }
func (*OrderId) ProtoMessage()    {}
func (*OrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{2}
}

func (m *OrderId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderId.Unmarshal(m, b)
}
func (m *OrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderId.Marshal(b, m, deterministic)
}
func (m *OrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderId.Merge(m, src)
}
func (m *OrderId) XXX_Size() int {
	return xxx_messageInfo_OrderId.Size(m)
}
func (m *OrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderId.DiscardUnknown(m)
}

var xxx_messageInfo_OrderId proto.InternalMessageInfo

func (m *OrderId) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderId) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Orders struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{3}
}

func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (m *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(m, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Req struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Asc                  bool     `protobuf:"varint,5,opt,name=asc,proto3" json:"asc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{4}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Req) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Req) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *Req) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Req) GetAsc() bool {
	if m != nil {
		return m.Asc
	}
	return false
}

func init() {
	proto.RegisterType((*Order)(nil), "order_service.Order")
	proto.RegisterType((*NewOrder)(nil), "order_service.NewOrder")
	proto.RegisterType((*OrderId)(nil), "order_service.OrderId")
	proto.RegisterType((*Orders)(nil), "order_service.Orders")
	proto.RegisterType((*Req)(nil), "order_service.Req")
}

func init() {
	proto.RegisterFile("order_service.proto", fileDescriptor_93a121d2d2ec3d32)
}

var fileDescriptor_93a121d2d2ec3d32 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0x6e, 0x92, 0xe6, 0x47, 0x5f, 0xaa, 0xc8, 0xb3, 0x6e, 0x87, 0x05, 0xa1, 0xe4, 0x24, 0x22,
	0x15, 0x2a, 0x08, 0x5a, 0x14, 0x56, 0xc5, 0x92, 0x8b, 0x42, 0xc4, 0x8b, 0x97, 0x25, 0xcd, 0xbc,
	0x6a, 0x30, 0xee, 0x34, 0x33, 0x13, 0xc5, 0x3f, 0xcd, 0xb3, 0xff, 0x98, 0xcc, 0x9b, 0xa4, 0xb0,
	0x25, 0x7b, 0xf0, 0x36, 0xdf, 0x8f, 0x97, 0xf7, 0xcd, 0xc7, 0x04, 0xee, 0x2b, 0x2d, 0x49, 0xaf,
	0x0d, 0xe9, 0x9f, 0x6d, 0x43, 0xa7, 0xd7, 0x5a, 0x59, 0x85, 0x77, 0xb6, 0xc8, 0xe2, 0x4f, 0x00,
	0xf1, 0x47, 0xc7, 0xe0, 0x5d, 0x08, 0x5b, 0x29, 0x82, 0x93, 0xe0, 0xd1, 0x41, 0x15, 0xb6, 0x12,
	0x8f, 0x21, 0xbd, 0x54, 0xea, 0xfb, 0xba, 0x95, 0x22, 0x64, 0x32, 0x71, 0xb0, 0x64, 0x61, 0x30,
	0xa4, 0x9d, 0x10, 0x79, 0xc1, 0xc1, 0x52, 0xe2, 0x12, 0xb2, 0x7e, 0xa8, 0x37, 0xb6, 0xb5, 0xbf,
	0xc5, 0x3e, 0x2b, 0x37, 0x18, 0x8f, 0x20, 0xb6, 0xca, 0xd6, 0x9d, 0x88, 0x59, 0xf0, 0x00, 0x1f,
	0x02, 0x34, 0x9a, 0x6a, 0x4b, 0x72, 0x5d, 0x5b, 0x91, 0xb0, 0x74, 0x30, 0x32, 0x2b, 0xeb, 0xe4,
	0xe1, 0x5a, 0x4e, 0x72, 0xea, 0xe5, 0x91, 0x59, 0xd9, 0xe2, 0x3d, 0x64, 0x1f, 0xe8, 0xd7, 0x7c,
	0xfa, 0xc7, 0x10, 0xf3, 0x45, 0x39, 0x7b, 0x7e, 0x76, 0x74, 0xba, 0xdd, 0x05, 0x0f, 0x55, 0xde,
	0x52, 0xbc, 0x80, 0x94, 0x71, 0x29, 0x51, 0x40, 0xaa, 0xfc, 0x71, 0xfc, 0xd6, 0x04, 0xdd, 0x05,
	0x1a, 0x35, 0x6c, 0x2c, 0x7f, 0x30, 0xae, 0x3c, 0x28, 0x9e, 0x43, 0xc2, 0xa3, 0x06, 0x9f, 0x40,
	0xc2, 0x56, 0x23, 0x82, 0x93, 0x68, 0xe7, 0xc6, 0xd1, 0x53, 0xf4, 0x10, 0x55, 0xd4, 0xe3, 0x02,
	0x12, 0x75, 0x75, 0x65, 0xc8, 0xf2, 0xb6, 0xb8, 0x1a, 0x91, 0x5b, 0xd6, 0xb5, 0x3f, 0xda, 0x9b,
	0x65, 0x0c, 0x9c, 0xdb, 0x50, 0xad, 0x9b, 0x6f, 0x53, 0xef, 0x1e, 0x21, 0xc2, 0xbe, 0x51, 0xda,
	0x8e, 0x9d, 0xf3, 0x19, 0xef, 0x41, 0x54, 0x9b, 0x86, 0xdb, 0xce, 0x2a, 0x77, 0x3c, 0xfb, 0x1b,
	0xc2, 0x21, 0x87, 0xf8, 0xe4, 0x13, 0xe1, 0x39, 0xe4, 0x6f, 0xb9, 0x6a, 0xdf, 0xe0, 0x6c, 0xe0,
	0xe5, 0x2c, 0x5b, 0xec, 0xe1, 0x4b, 0xc8, 0x2e, 0xc8, 0xfa, 0xc9, 0xc5, 0x9c, 0xa7, 0x94, 0x3b,
	0x67, 0xcf, 0xe1, 0xf0, 0x82, 0xec, 0xaa, 0xeb, 0xc6, 0xea, 0xf0, 0x96, 0xaf, 0xa2, 0x7e, 0xf9,
	0x60, 0x6e, 0xd6, 0x14, 0x7b, 0xf8, 0x1a, 0xf2, 0xcf, 0xfc, 0x02, 0xfc, 0xee, 0xe3, 0x5b, 0xbe,
	0xe9, 0x41, 0xec, 0x5c, 0xfe, 0x0a, 0xf2, 0x77, 0xd4, 0xd1, 0x34, 0xff, 0x9f, 0xd9, 0xdf, 0x88,
	0x2f, 0x8b, 0xaf, 0xb4, 0xe1, 0x5f, 0xe9, 0xe9, 0x96, 0xe3, 0x32, 0x61, 0xf2, 0xd9, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd5, 0x70, 0xd7, 0xcd, 0x76, 0x03, 0x00, 0x00,
}
