// Code generated by protoc-gen-go. DO NOT EDIT.
// source: other_service.proto

package other_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateOtherRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfessionId         string   `protobuf:"bytes,3,opt,name=profession_id,json=professionId,proto3" json:"profession_id,omitempty"`
	CompanyId            string   `protobuf:"bytes,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOtherRequest) Reset()         { *m = UpdateOtherRequest{} }
func (m *UpdateOtherRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOtherRequest) ProtoMessage()    {}
func (*UpdateOtherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_687930dda62c0662, []int{0}
}

func (m *UpdateOtherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOtherRequest.Unmarshal(m, b)
}
func (m *UpdateOtherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOtherRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOtherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOtherRequest.Merge(m, src)
}
func (m *UpdateOtherRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOtherRequest.Size(m)
}
func (m *UpdateOtherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOtherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOtherRequest proto.InternalMessageInfo

func (m *UpdateOtherRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateOtherRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateOtherRequest) GetProfessionId() string {
	if m != nil {
		return m.ProfessionId
	}
	return ""
}

func (m *UpdateOtherRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

type OtherID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OtherID) Reset()         { *m = OtherID{} }
func (m *OtherID) String() string { return proto.CompactTextString(m) }
func (*OtherID) ProtoMessage()    {}
func (*OtherID) Descriptor() ([]byte, []int) {
	return fileDescriptor_687930dda62c0662, []int{1}
}

func (m *OtherID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherID.Unmarshal(m, b)
}
func (m *OtherID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherID.Marshal(b, m, deterministic)
}
func (m *OtherID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherID.Merge(m, src)
}
func (m *OtherID) XXX_Size() int {
	return xxx_messageInfo_OtherID.Size(m)
}
func (m *OtherID) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherID.DiscardUnknown(m)
}

var xxx_messageInfo_OtherID proto.InternalMessageInfo

func (m *OtherID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateOtherRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProfessionId         string   `protobuf:"bytes,2,opt,name=profession_id,json=professionId,proto3" json:"profession_id,omitempty"`
	CompanyId            string   `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOtherRequest) Reset()         { *m = CreateOtherRequest{} }
func (m *CreateOtherRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOtherRequest) ProtoMessage()    {}
func (*CreateOtherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_687930dda62c0662, []int{2}
}

func (m *CreateOtherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOtherRequest.Unmarshal(m, b)
}
func (m *CreateOtherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOtherRequest.Marshal(b, m, deterministic)
}
func (m *CreateOtherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOtherRequest.Merge(m, src)
}
func (m *CreateOtherRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOtherRequest.Size(m)
}
func (m *CreateOtherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOtherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOtherRequest proto.InternalMessageInfo

func (m *CreateOtherRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOtherRequest) GetProfessionId() string {
	if m != nil {
		return m.ProfessionId
	}
	return ""
}

func (m *CreateOtherRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateOtherRequest)(nil), "other_service.UpdateOtherRequest")
	proto.RegisterType((*OtherID)(nil), "other_service.OtherID")
	proto.RegisterType((*CreateOtherRequest)(nil), "other_service.CreateOtherRequest")
}

func init() {
	proto.RegisterFile("other_service.proto", fileDescriptor_687930dda62c0662)
}

var fileDescriptor_687930dda62c0662 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x2f, 0xc9, 0x48,
	0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x45, 0x11, 0x54, 0xaa, 0xe1, 0x12, 0x0a, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xf5, 0x07, 0x09,
	0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a,
	0x30, 0x81, 0x45, 0xc0, 0x6c, 0x21, 0x65, 0x2e, 0xde, 0x82, 0xa2, 0xfc, 0xb4, 0xd4, 0xe2, 0xe2,
	0xcc, 0xfc, 0xbc, 0xf8, 0xcc, 0x14, 0x09, 0x66, 0xb0, 0x24, 0x0f, 0x42, 0xd0, 0x33, 0x45, 0x48,
	0x96, 0x8b, 0x2b, 0x39, 0x3f, 0xb7, 0x20, 0x31, 0xaf, 0x12, 0xa4, 0x82, 0x05, 0xac, 0x82, 0x13,
	0x2a, 0xe2, 0x99, 0xa2, 0x24, 0xc9, 0xc5, 0x0e, 0xb6, 0xd7, 0xd3, 0x05, 0xdd, 0x4a, 0xa5, 0x1c,
	0x2e, 0x21, 0xe7, 0xa2, 0x54, 0x74, 0x87, 0xc1, 0x1c, 0xc2, 0x88, 0xcf, 0x21, 0x4c, 0x04, 0x1d,
	0xc2, 0x8c, 0xe6, 0x10, 0xa3, 0x65, 0x8c, 0x5c, 0x3c, 0x60, 0x8b, 0x82, 0x21, 0xe1, 0x22, 0xe4,
	0xc5, 0xc5, 0x8d, 0x64, 0xbd, 0x90, 0xa2, 0x1e, 0x6a, 0x58, 0x62, 0x3a, 0x4d, 0x4a, 0x0c, 0x4d,
	0x09, 0xd4, 0x63, 0x4a, 0x0c, 0x20, 0xb3, 0x90, 0xc2, 0x18, 0xc3, 0x2c, 0xcc, 0xf0, 0xc7, 0x6d,
	0x96, 0x93, 0x44, 0x94, 0x58, 0x7a, 0x6a, 0x1e, 0x38, 0x2a, 0xf5, 0x51, 0xd4, 0x24, 0xb1, 0x81,
	0x05, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0x21, 0x5c, 0xc6, 0xf6, 0x01, 0x00, 0x00,
}
