// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_service.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RenewTokenReq struct {
	Useragent            string   `protobuf:"bytes,1,opt,name=useragent,proto3" json:"useragent,omitempty"`
	Userip               string   `protobuf:"bytes,2,opt,name=userip,proto3" json:"userip,omitempty"`
	Invaccesstoken       string   `protobuf:"bytes,3,opt,name=invaccesstoken,proto3" json:"invaccesstoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewTokenReq) Reset()         { *m = RenewTokenReq{} }
func (m *RenewTokenReq) String() string { return proto.CompactTextString(m) }
func (*RenewTokenReq) ProtoMessage()    {}
func (*RenewTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{0}
}

func (m *RenewTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewTokenReq.Unmarshal(m, b)
}
func (m *RenewTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewTokenReq.Marshal(b, m, deterministic)
}
func (m *RenewTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewTokenReq.Merge(m, src)
}
func (m *RenewTokenReq) XXX_Size() int {
	return xxx_messageInfo_RenewTokenReq.Size(m)
}
func (m *RenewTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RenewTokenReq proto.InternalMessageInfo

func (m *RenewTokenReq) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

func (m *RenewTokenReq) GetUserip() string {
	if m != nil {
		return m.Userip
	}
	return ""
}

func (m *RenewTokenReq) GetInvaccesstoken() string {
	if m != nil {
		return m.Invaccesstoken
	}
	return ""
}

type RenewTokenRes struct {
	Newaccesstoken       string   `protobuf:"bytes,1,opt,name=newaccesstoken,proto3" json:"newaccesstoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewTokenRes) Reset()         { *m = RenewTokenRes{} }
func (m *RenewTokenRes) String() string { return proto.CompactTextString(m) }
func (*RenewTokenRes) ProtoMessage()    {}
func (*RenewTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{1}
}

func (m *RenewTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewTokenRes.Unmarshal(m, b)
}
func (m *RenewTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewTokenRes.Marshal(b, m, deterministic)
}
func (m *RenewTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewTokenRes.Merge(m, src)
}
func (m *RenewTokenRes) XXX_Size() int {
	return xxx_messageInfo_RenewTokenRes.Size(m)
}
func (m *RenewTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_RenewTokenRes proto.InternalMessageInfo

func (m *RenewTokenRes) GetNewaccesstoken() string {
	if m != nil {
		return m.Newaccesstoken
	}
	return ""
}

type ValidateUserReq struct {
	Accesstoken          string   `protobuf:"bytes,1,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
	Userip               string   `protobuf:"bytes,2,opt,name=userip,proto3" json:"userip,omitempty"`
	Useragent            string   `protobuf:"bytes,3,opt,name=useragent,proto3" json:"useragent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUserReq) Reset()         { *m = ValidateUserReq{} }
func (m *ValidateUserReq) String() string { return proto.CompactTextString(m) }
func (*ValidateUserReq) ProtoMessage()    {}
func (*ValidateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{2}
}

func (m *ValidateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUserReq.Unmarshal(m, b)
}
func (m *ValidateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUserReq.Marshal(b, m, deterministic)
}
func (m *ValidateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUserReq.Merge(m, src)
}
func (m *ValidateUserReq) XXX_Size() int {
	return xxx_messageInfo_ValidateUserReq.Size(m)
}
func (m *ValidateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUserReq proto.InternalMessageInfo

func (m *ValidateUserReq) GetAccesstoken() string {
	if m != nil {
		return m.Accesstoken
	}
	return ""
}

func (m *ValidateUserReq) GetUserip() string {
	if m != nil {
		return m.Userip
	}
	return ""
}

func (m *ValidateUserReq) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

type ValidateUserRes struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Accesstoken          string   `protobuf:"bytes,2,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUserRes) Reset()         { *m = ValidateUserRes{} }
func (m *ValidateUserRes) String() string { return proto.CompactTextString(m) }
func (*ValidateUserRes) ProtoMessage()    {}
func (*ValidateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{3}
}

func (m *ValidateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUserRes.Unmarshal(m, b)
}
func (m *ValidateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUserRes.Marshal(b, m, deterministic)
}
func (m *ValidateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUserRes.Merge(m, src)
}
func (m *ValidateUserRes) XXX_Size() int {
	return xxx_messageInfo_ValidateUserRes.Size(m)
}
func (m *ValidateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUserRes proto.InternalMessageInfo

func (m *ValidateUserRes) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateUserRes) GetAccesstoken() string {
	if m != nil {
		return m.Accesstoken
	}
	return ""
}

func (m *ValidateUserRes) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Secondname           string   `protobuf:"bytes,3,opt,name=secondname,proto3" json:"secondname,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetSecondname() string {
	if m != nil {
		return m.Secondname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpReq struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Secondname           string   `protobuf:"bytes,2,opt,name=secondname,proto3" json:"secondname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{5}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *SignUpReq) GetSecondname() string {
	if m != nil {
		return m.Secondname
	}
	return ""
}

func (m *SignUpReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Userip               string   `protobuf:"bytes,3,opt,name=userip,proto3" json:"userip,omitempty"`
	Useragent            string   `protobuf:"bytes,4,opt,name=useragent,proto3" json:"useragent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{6}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignInReq) GetUserip() string {
	if m != nil {
		return m.Userip
	}
	return ""
}

func (m *SignInReq) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

type Token struct {
	Accesstoken          string   `protobuf:"bytes,1,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{7}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccesstoken() string {
	if m != nil {
		return m.Accesstoken
	}
	return ""
}

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{8}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{9}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RenewTokenReq)(nil), "auth_service.RenewTokenReq")
	proto.RegisterType((*RenewTokenRes)(nil), "auth_service.RenewTokenRes")
	proto.RegisterType((*ValidateUserReq)(nil), "auth_service.ValidateUserReq")
	proto.RegisterType((*ValidateUserRes)(nil), "auth_service.ValidateUserRes")
	proto.RegisterType((*User)(nil), "auth_service.User")
	proto.RegisterType((*SignUpReq)(nil), "auth_service.SignUpReq")
	proto.RegisterType((*SignInReq)(nil), "auth_service.SignInReq")
	proto.RegisterType((*Token)(nil), "auth_service.Token")
	proto.RegisterType((*UserId)(nil), "auth_service.UserId")
	proto.RegisterType((*Empty)(nil), "auth_service.Empty")
}

func init() {
	proto.RegisterFile("auth_service.proto", fileDescriptor_0f39bb026ca10b68)
}

var fileDescriptor_0f39bb026ca10b68 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xcd, 0x6e, 0xb2, 0xdb, 0x66, 0x5a, 0x8a, 0x34, 0x14, 0xba, 0x5a, 0x3e, 0x54, 0xf9, 0x80,
	0x38, 0x15, 0x09, 0x84, 0xa0, 0x47, 0x10, 0x48, 0xe4, 0x02, 0xd2, 0x96, 0x72, 0xe0, 0x82, 0x4c,
	0x76, 0x48, 0x2d, 0x1a, 0xef, 0xb2, 0x76, 0x12, 0xf1, 0x4b, 0xb8, 0xf3, 0x97, 0xf8, 0x43, 0xc8,
	0xf6, 0x36, 0x59, 0x9b, 0x6e, 0xd4, 0xe3, 0xbc, 0xe7, 0x37, 0xf3, 0xec, 0x99, 0x31, 0x20, 0x5f,
	0xe8, 0x8b, 0xaf, 0x8a, 0x9a, 0xa5, 0x98, 0xd2, 0x49, 0xdd, 0x54, 0xba, 0xc2, 0xfd, 0x2e, 0xc6,
	0xe6, 0x70, 0xab, 0x20, 0x49, 0xab, 0x4f, 0xd5, 0x0f, 0x92, 0x05, 0xfd, 0xc4, 0x07, 0x30, 0x5e,
	0x28, 0x6a, 0xf8, 0x8c, 0xa4, 0xce, 0xa2, 0xe3, 0xe8, 0xc9, 0xb8, 0xd8, 0x00, 0x78, 0x0f, 0x52,
	0x13, 0x88, 0x3a, 0x8b, 0x2d, 0xd5, 0x46, 0xf8, 0x18, 0x0e, 0x84, 0x5c, 0xf2, 0xe9, 0x94, 0x94,
	0xd2, 0x26, 0x55, 0x36, 0xb4, 0x7c, 0x80, 0xb2, 0x97, 0x7e, 0x39, 0x65, 0x84, 0x92, 0x56, 0x5d,
	0xa1, 0xab, 0x19, 0xa0, 0x4c, 0xc0, 0xed, 0xcf, 0xfc, 0x52, 0x94, 0x5c, 0xd3, 0xb9, 0xa2, 0xc6,
	0x38, 0x3d, 0x86, 0xbd, 0xff, 0x75, 0x5d, 0xa8, 0xd7, 0xad, 0x77, 0xc7, 0x61, 0x70, 0x47, 0xc6,
	0xc3, 0x52, 0x0a, 0x0f, 0x21, 0x59, 0x1a, 0xc8, 0x16, 0xd9, 0x2d, 0x5c, 0x10, 0x1a, 0x88, 0x7b,
	0x0d, 0x4c, 0xde, 0xb6, 0x55, 0xda, 0x88, 0xfd, 0x89, 0x60, 0x64, 0x72, 0xe3, 0x01, 0xc4, 0x6d,
	0xd6, 0x71, 0x11, 0x8b, 0xd2, 0x38, 0xfb, 0x2e, 0x1a, 0xa5, 0x25, 0x9f, 0x53, 0x9b, 0x70, 0x03,
	0xe0, 0x23, 0x00, 0x45, 0xd3, 0x4a, 0x96, 0x96, 0x76, 0x29, 0x3b, 0x08, 0xe6, 0xb0, 0x6b, 0x0a,
	0x58, 0x76, 0x64, 0xd9, 0x75, 0x6c, 0xae, 0x40, 0x73, 0x2e, 0x2e, 0xb3, 0xc4, 0x12, 0x2e, 0x30,
	0x8a, 0x9a, 0x2b, 0xb5, 0xaa, 0x9a, 0x32, 0x4b, 0x9d, 0xe2, 0x2a, 0x66, 0xbf, 0x23, 0x18, 0x9f,
	0x89, 0x99, 0x3c, 0xaf, 0xdb, 0xb9, 0xd8, 0x38, 0x8b, 0xb6, 0x3b, 0x8b, 0xb7, 0x3a, 0x1b, 0xf6,
	0x39, 0x1b, 0xf5, 0x39, 0x4b, 0x02, 0x67, 0xca, 0x19, 0x9b, 0xd8, 0x81, 0x5d, 0xcb, 0xa3, 0x3e,
	0x79, 0xec, 0xcb, 0x3b, 0x63, 0x31, 0xec, 0x1f, 0x8b, 0x51, 0x38, 0x16, 0xa7, 0x90, 0xd8, 0xa9,
	0xbd, 0xc1, 0xdc, 0xb9, 0xae, 0xc6, 0x57, 0x5d, 0x65, 0x19, 0xa4, 0xa6, 0xdb, 0x93, 0x32, 0xec,
	0x37, 0xdb, 0x81, 0xe4, 0xdd, 0xbc, 0xd6, 0xbf, 0x9e, 0xfd, 0x8d, 0x61, 0xef, 0xf5, 0x42, 0x5f,
	0x9c, 0xb9, 0xbd, 0xc4, 0x53, 0x48, 0xdd, 0xdb, 0xe3, 0xd1, 0x89, 0xb7, 0xc4, 0xeb, 0x8e, 0xe4,
	0x87, 0x3e, 0xe1, 0x2a, 0xb0, 0x01, 0xbe, 0x72, 0xd2, 0x89, 0xbc, 0x4e, 0x6a, 0xdf, 0x2c, 0xbf,
	0xe3, 0x13, 0xf6, 0x5e, 0x6c, 0x80, 0x1f, 0x60, 0xbf, 0x3b, 0xf9, 0xf8, 0xd0, 0x3f, 0x16, 0x2c,
	0x60, 0xbe, 0x95, 0x56, 0x6c, 0x80, 0xef, 0x01, 0x36, 0xdb, 0x8e, 0xf7, 0xfd, 0xe3, 0xde, 0xb7,
	0x93, 0x6f, 0x21, 0x4d, 0xa6, 0x17, 0xb0, 0x63, 0xdc, 0x7f, 0x5c, 0x68, 0x0c, 0xbc, 0xdb, 0xe7,
	0xcb, 0xaf, 0x03, 0xd9, 0xe0, 0xcd, 0xd1, 0x97, 0xbb, 0x33, 0x92, 0xf6, 0xdf, 0x7b, 0xda, 0x3d,
	0xf0, 0x2d, 0xb5, 0xd8, 0xf3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0xd0, 0xbb, 0x52, 0x21,
	0x05, 0x00, 0x00,
}
